Repository likelion-reactproject-lab12/together, pull requests merged in 2023-04, with the labels that each got.

#122 [setting] 스토리북을 위한 환경설정 및 secondary color 수정 #121
  .storybook/preview.js
  .storybook/preview.jsx
  package-lock.json
  src/components/landing/MessageAd.stories.jsx
  src/styles/GlobalStyle.ts
Labels: remove or edit, setting

#131 랜딩 TS 마이그레이션 #129
  src/components/landing/CarouselAutoFirst.tsx
  src/components/landing/CarouselAutoSecond.tsx
  src/components/landing/CarouselScroll.tsx
  src/components/landing/MessageAd.tsx
  src/components/landing/MessageTitle.tsx
  src/components/landing/PrimaryButton.tsx
  src/containers/landingpage/ScrollSectionAd.tsx
  src/containers/landingpage/ScrollSectionNow.tsx
  src/containers/landingpage/ScrollSectionOriginal.tsx
  src/containers/landingpage/ScrollSectionTitle.tsx
  src/pages/LandingPage.tsx
  src/types/carousel.ts
Labels: refactor

#128 메인, 헤더, 검색 typescript 마이그레이션
  package-lock.json
  package.json
  src/components/a11yhidden/A11yHidden.tsx
  src/components/carousel/Carousel.tsx
  src/components/carousel/MainBanner.tsx
  src/components/header/Header.tsx
  src/components/header/LogoModal.tsx
  src/components/logout/LogoutModal.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalPortal.jsx
  src/components/modal/ModalPortal.tsx
  src/components/popup/Popup.tsx
  src/components/profile/ProfileDeleteModal.tsx
  src/components/search/SearchBar.tsx
  src/components/search/SearchHistory.tsx
  src/components/search/SearchModal.tsx
  src/components/search/SearchPopular.tsx
  src/components/search/SearchResult.tsx
  src/components/svg/Svg.jsx
  src/components/svg/Svg.tsx
  src/firebase/firestore/useReadData.js
  src/hooks/useDebounce.ts
  src/hooks/useModal.js
  src/hooks/useModal.ts
  src/hooks/useThrottle.ts
  src/pages/MainPage.tsx
  src/pages/ProfileEdit.jsx
  src/pages/SearchPage.tsx
  src/store/modalState.js
  src/store/modalState.ts
  src/store/search/index.ts
  src/store/search/searchDataState.ts
  src/store/search/searchHistoryState.js
  src/store/search/searchHistoryState.ts
  src/store/search/searchKeywordState.ts
  src/styles/SearchBarStyles.tsx
  src/theme/utils.ts
  src/types/carousel.ts
  src/types/programs.ts
  src/types/search.ts
Labels: refactor

#134 커스텀훅 마이그레이션 및 리팩토링
  src/components/carousel/Carousel.tsx
  src/components/carousel/MainBanner.tsx
  src/components/landing/CarouselAutoFirst.tsx
  src/components/landing/CarouselAutoSecond.tsx
  src/components/landing/CarouselScroll.tsx
  src/firebase/README.md
  src/firebase/auth/README.md
  src/firebase/auth/useAuthState.ts
  src/firebase/auth/useSignIn.ts
  src/firebase/auth/useSignOut.ts
  src/firebase/auth/useSignUp.ts
  src/firebase/firestore/README.md
  src/firebase/firestore/index.ts
  src/firebase/firestore/useCreateAuthUser.ts
  src/firebase/firestore/useCreateData.ts
  src/firebase/firestore/useDataState.js
  src/firebase/firestore/useDeleteData.ts
  src/firebase/firestore/useReadData.ts
  src/firebase/firestore/useReadSearchData.ts
  src/firebase/firestore/useUpdateData.js
  src/firebase/firestore/useWriteBatchData.js
  src/firebase/storage/README.md
  src/firebase/storage/index.ts
  src/firebase/storage/useDeleteFile.ts
  src/firebase/storage/useDownloadURL.js
  src/firebase/storage/useUploadFile.js
  src/pages/FindIdPage.tsx
  src/pages/FindPwPage.jsx
  src/pages/Layout.tsx
  src/pages/NotFound.tsx
  src/pages/ProfileCreate.tsx
  src/pages/ProfileEdit.tsx
  src/pages/ProfilePage.tsx
  src/types/carousel.ts
  src/types/programs.ts
Labels: refactor

#136 getFontStyle 함수 오류 해결 및 타입 명시 #125
  src/theme/tokens.ts
  src/theme/utils.ts
Labels: bug, chore

#139 [refactor] 리팩토링
  src/components/login/LoginForm.tsx
  src/components/profile/ProfileDeleteModal.tsx
  src/components/register/RegisterForm.tsx
  src/firebase/firestore/useCreateAuthUser.ts
  src/pages/ProfileCreate.tsx
  src/styles/ProfileStyles.ts
  src/types/signForm.ts
Labels: refactor

#143 불필요 주석 및 파일 삭제, HTML 문법 오류 수정 #133
  index.html
  src/components/landing/CarouselScroll.tsx
  src/components/landing/MessageAd.stories.jsx
  src/components/landing/MessageTitle.stories.jsx
  src/components/landing/PrimaryButton.stories.jsx
  src/components/svg/Svg.tsx
  src/containers/landingpage/ScrollSectionAd.tsx
  src/containers/landingpage/ScrollSectionNow.tsx
  src/containers/landingpage/ScrollSectionOriginal.tsx
  src/containers/landingpage/ScrollSectionTitle.tsx
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Introduction.mdx
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: refactor, remove or edit
