Repository likelion-reactproject-lab12/together, pull requests merged in 2023-03, with the labels that each got.

#6 스타일 시스템 세팅 #5
  src/assets/css_sprites.png
  src/pages/Layout.jsx
  src/theme/tokens.js
  src/theme/utils.js
Labels: setting

#11 header 기능 추가 #10
  src/App.jsx
  src/assets/css_sprites.png
  src/assets/sprites.png
  src/components/A11yHidden.jsx
  src/components/header/Header.jsx
  src/pages/Layout.jsx
  src/pages/MainPage.jsx
Labels: style, refactor, feat

#20 [chore] 파일 경로, import 수정
  src/components/a11yhidden/A11yHidden.jsx
  src/components/header/Header.jsx
Labels: remove or edit, chore

#26 [bug] 윈도우창 바탕 컬러 버그 수정 #23
  index.html
  src/App.jsx
  src/pages/Layout.jsx
  src/styles/GlobalStyle.jsx
Labels: bug, question/note

#32 [config] 환경설정 및 공통스타일 추가 수정
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  package-lock.json
  package.json
  src/pages/Layout.jsx
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Introduction.mdx
  src/stories/Page.jsx
  src/stories/Page.stories.js
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/GlobalStyle.jsx
  vite.config.js
Labels: bug, style, setting

#33 로그아웃 모달 창 마크업 및 스타일링
  index.html
  src/components/logout/LogoutModal.jsx
  src/components/modal/ModalPortal.jsx
Labels: style, feat

#37 [feat] 회원가입 구현
  src/App.jsx
  src/components/button/FormButton.jsx
  src/components/forminput/FormInput.jsx
  src/components/register/RegisterForm.jsx
  src/pages/RegisterPage.jsx
  src/styles/GlobalStyle.jsx
Labels: style, chore, feat

#38 스토리북 애드온(viewport 커스텀, A11y 설치) 설정 #36
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/assets/sprites.svg
  src/stories/button.css
  src/styles/GlobalStyle.jsx
Labels: remove or edit, setting

#39 [setting] 스토리북 애드온 설치
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/landing/Button2.css
  src/components/landing/Button2.jsx
  src/components/landing/Button2.stories.js
  src/components/landing/IconButton.css
  src/components/landing/IconButton.jsx
  src/components/landing/IconButton.stories.js
  src/pages/MainPage.jsx
Labels: setting

#41 팝업 마크업 및 스타일링
  src/assets/popup/desktop.png
  src/assets/popup/mobile.png
  src/assets/popup/tablet.png
  src/components/logout/LogoutModal.jsx
  src/components/popup/Popup.jsx
Labels: style

#43 [feat] 로그인 구현
  src/App.jsx
  src/components/button/FormButton.jsx
  src/components/forminput/FormInput.jsx
  src/components/login/LoginForm.jsx
  src/components/register/RegisterForm.jsx
  src/firebase/auth/useSignIn.js
  src/pages/LoginPage.jsx
  src/styles/FormStyles.jsx
  src/styles/GlobalStyle.jsx
Labels: style, refactor, feat

#50 검색 #29
  src/App.jsx
  src/assets/sprite.svg
  src/components/header/Header.jsx
  src/components/modal/Modal.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchHistory.jsx
  src/components/search/SearchModal.jsx
  src/components/search/SearchPopular.jsx
  src/components/search/SearchResult.jsx
  src/components/svg/Svg.jsx
  src/firebase/app.js
  src/firebase/firestore/useReadSearchData.js
  src/hooks/useDebounce.js
  src/pages/SearchPage.jsx
  src/store/search/index.js
  src/store/search/searchDataState.js
  src/store/search/searchHistoryState.js
  src/store/search/searchKeywordState.js
Labels: style, feat

#53 [style] footer 마크업 및 디자인
  src/components/footer/Footer.jsx
  src/pages/MainPage.jsx
  src/styles/GlobalStyle.jsx
Labels: style, refactor

#56 헤더 리팩토링
  src/assets/sprite.svg
  src/components/header/Header.jsx
  src/components/svg/Svg.jsx
  src/hooks/useThrottle.js
  src/pages/Layout.jsx
  src/pages/MainPage.jsx
Labels: refactor

#54 팝업 버튼 기능 구현
  src/components/popup/Popup.jsx
  src/pages/MainPage.jsx
Labels: feat

#67 로그아웃 모달 버튼 기능 구현
  src/App.jsx
  src/components/logout/LogoutModal.jsx
  src/pages/LandingPage.jsx
  src/pages/MainPage.jsx
Labels: feat

#69 프로필 호버 드롭다운 구현
  src/assets/profile_4.png
  src/components/header/Header.jsx
  src/components/header/LogoModal.jsx
Labels: style, feat

#71 페이지 라우팅 설정 및 전체적인 리팩토링
  index.html
  src/App.jsx
  src/PrivateRoute.jsx
  src/assets/sprite.svg
  src/assets/sprites.svg
  src/components/footer/Footer.jsx
  src/components/header/Header.jsx
  src/components/header/LogoModal.jsx
  src/components/landing/Button2.css
  src/components/landing/Button2.jsx
  src/components/landing/Button2.stories.js
  src/components/landing/IconButton.css
  src/components/landing/IconButton.jsx
  src/components/landing/IconButton.stories.js
  src/components/login/LoginForm.jsx
  src/components/logout/LogoutModal.jsx
  src/components/modal/Modal.jsx
  src/components/modal/ModalPortal.jsx
  src/components/popup/Popup.jsx
  src/components/register/RegisterForm.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchHistory.jsx
  src/components/search/SearchModal.jsx
  src/components/search/SearchPopular.jsx
  src/components/search/SearchResult.jsx
  src/components/svg/Svg.jsx
  src/firebase/auth/useAuthState.js
  src/main.jsx
  src/pages/FindIdPage.jsx
  src/pages/FindPwPage.jsx
  src/pages/LandingPage.jsx
  src/pages/Layout.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/NotFound.jsx
  src/pages/ProfilePage.jsx
  src/pages/RegisterPage.jsx
  src/pages/SearchPage.jsx
Labels: style, refactor, remove or edit, chore, feat

#72 검색 페이지
  src/assets/sprite.svg
  src/components/header/Header.jsx
  src/components/search/Carousel.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchHistory.jsx
  src/components/search/SearchModal.jsx
  src/components/search/SearchPopular.jsx
  src/components/search/SearchResult.jsx
  src/components/svg/Svg.jsx
  src/firebase/firestore/useReadSearchData.js
  src/hooks/useModal.js
  src/pages/Layout.jsx
  src/pages/SearchPage.jsx
  src/store/modalState.js
  src/store/search/searchDataState.js
  src/styles/SearchBarStyles.jsx
Labels: style, refactor, feat

#75 랜딩페이지 스타일링 완료 및 프로필페이지 라우팅, svg 오류 해결 #13
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  .storybook/preview.jsx
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.jsx
  src/assets/landing-img/bg-desktop.png
  src/assets/landing-img/bg-mobile-modified.png
  src/assets/landing-img/bg-mobile.png
  src/assets/landing-img/bg-tablet.png
  src/assets/landing-img/contents-img/fun-food-desktop.png
  src/assets/landing-img/contents-img/fun-food-mob-and-tabl.png
  src/assets/landing-img/contents-img/fun-letmein-desktop.png
  src/assets/landing-img/contents-img/fun-letmein-mob-and-tabl.png
  src/assets/landing-img/contents-img/fun-manager-desktop.png
  src/assets/landing-img/contents-img/fun-manager-mob-and-tabl.png
  src/assets/landing-img/contents-img/fun-quiz-desktop.png
  src/assets/landing-img/contents-img/fun-quiz-mob-and-tabl.png
  src/assets/landing-img/contents-img/fun-shurup-desktop.png
  src/assets/landing-img/contents-img/fun-shurup-mob-and-tabl.png
  src/assets/landing-img/contents-img/org-alchol-mob-and-tabl.png
  src/assets/landing-img/contents-img/org-body-desktop.png
  src/assets/landing-img/contents-img/org-bomul-desktop.png
  src/assets/landing-img/contents-img/org-bomul-mob-and-tabl.png
  src/assets/landing-img/contents-img/org-food-desktop.png
  src/assets/landing-img/contents-img/org-island-desktop.png
  src/assets/landing-img/contents-img/org-island-mob-and-tabl.png
  src/assets/landing-img/contents-img/org-love-desktop.png
  src/assets/landing-img/contents-img/org-love-mob-and-tabl.png
  src/assets/sprite.svg
  src/assets/sprites.png
  src/components/landing/CarouselAuto.jsx
  src/components/landing/CarouselScroll.jsx
  src/components/landing/MessageAd.jsx
  src/components/landing/MessageAd.stories.jsx
  src/components/landing/MessageTitle.jsx
  src/components/landing/MessageTitle.stories.jsx
  src/components/landing/PrimaryButton.jsx
  src/components/landing/PrimaryButton.stories.jsx
  src/containers/landingpage/ScrollSectionAd.jsx
  src/containers/landingpage/ScrollSectionNow.jsx
  src/containers/landingpage/ScrollSectionOriginal.jsx
  src/containers/landingpage/ScrollSectionTitle.jsx
  src/pages/LandingPage.jsx
  src/pages/ProfileEdit.jsx
  src/styles/GlobalStyle.jsx
Labels: bug, style, chore, feat

#80 메인 배너 및 프로필 페이지 구현
  src/assets/sprite.svg
  src/components/carousel/MainBanner.jsx
  src/pages/MainPage.jsx
  src/pages/ProfilePage.jsx
Labels: style, feat

#83 스크롤 트리거 애니메이션 구현 #77 #13
  .vscode/settings.json
  src/components/landing/CarouselAuto.jsx
  src/components/landing/CarouselScroll.jsx
  src/components/landing/MessageAd.jsx
  src/containers/landingpage/ScrollSectionAd.jsx
  src/containers/landingpage/ScrollSectionNow.jsx
  src/containers/landingpage/ScrollSectionOriginal.jsx
  src/containers/landingpage/ScrollSectionTitle.jsx
  src/pages/LandingPage.jsx
Labels: chore, feat

#84 메인 페이지 캐로셀
  src/assets/main/desktop.png
  src/assets/main/mobile.png
  src/assets/main/tablet.png
  src/components/carousel/Carousel.jsx
  src/components/carousel/MainBanner.jsx
  src/components/header/Header.jsx
  src/components/landing/PrimaryButton.jsx
  src/components/search/SearchModal.jsx
  src/pages/MainPage.jsx
  src/pages/SearchPage.jsx
  src/theme/tokens.js
Labels: bug, style, feat

#87 프로필 페이지 렌더링 및 프로필 수정 페이지
  src/App.jsx
  src/PrivateRoute.jsx
  src/components/login/LoginForm.jsx
  src/components/profile/Profile.jsx
  src/pages/ProfileEdit.jsx
  src/pages/ProfilePage.jsx
  src/styles/FormStyles.jsx
Labels: bug, style, refactor, feat

#88 isLoading 컴포넌트 (스켈레톤)
  src/components/carousel/Carousel.jsx
  src/components/carousel/MainBanner.jsx
  src/components/loading/Skeleton.jsx
  src/components/loading/SkeletonBanner.jsx
  src/components/loading/SkeletonCarousel.jsx
Labels: style, feat

#81 프로필 추가 및 삭제
  src/App.jsx
  src/components/header/LogoModal.jsx
  src/components/profile/ProfileDeleteModal.jsx
  src/pages/ProfileCRUD.jsx
  src/pages/ProfileEdit.jsx
  src/pages/ProfilePage.jsx
Labels: feat

#92 검색, 메인, 헤더 리팩토링
  index.html
  src/assets/main/desktop.png
  src/assets/main/mobile.png
  src/assets/main/tablet.png
  src/components/carousel/Carousel.jsx
  src/components/carousel/MainBanner.jsx
  src/components/header/Header.jsx
  src/components/modal/ModalMiddlePortal.jsx
  src/components/search/SearchModal.jsx
  src/pages/MainPage.jsx
  src/pages/SearchPage.jsx
Labels: bug, style, refactor, remove or edit

#94 폴더&이미지 경로 수정 및 404 error page 스타일
  public/assets/landing-img/bg-desktop.png
  public/assets/landing-img/bg-mobile-modified.png
  public/assets/landing-img/bg-mobile.png
  public/assets/landing-img/bg-tablet.png
  public/assets/landing-img/contents-img/fun-food-desktop.png
  public/assets/landing-img/contents-img/fun-food-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-letmein-desktop.png
  public/assets/landing-img/contents-img/fun-letmein-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-manager-desktop.png
  public/assets/landing-img/contents-img/fun-manager-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-quiz-desktop.png
  public/assets/landing-img/contents-img/fun-quiz-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-shurup-desktop.png
  public/assets/landing-img/contents-img/fun-shurup-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-alchol-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-body-desktop.png
  public/assets/landing-img/contents-img/org-bomul-desktop.png
  public/assets/landing-img/contents-img/org-bomul-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-food-desktop.png
  public/assets/landing-img/contents-img/org-island-desktop.png
  public/assets/landing-img/contents-img/org-island-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-love-desktop.png
  public/assets/landing-img/contents-img/org-love-mob-and-tabl.png
  public/assets/popup/desktop.png
  public/assets/popup/mobile.png
  public/assets/popup/tablet.png
  public/assets/profile_1.png
  public/assets/profile_4.png
  public/assets/sprite.svg
  src/components/header/LogoModal.jsx
  src/components/landing/CarouselAuto.jsx
  src/components/landing/CarouselScroll.jsx
  src/components/popup/Popup.jsx
  src/components/svg/Svg.jsx
  src/containers/landingpage/ScrollSectionTitle.jsx
  src/pages/NotFound.jsx
  src/pages/ProfileEdit.jsx
Labels: style, refactor, chore

#100 로고모달창 프로필전환 버그
  src/components/header/LogoModal.jsx
Labels: bug, style, refactor

#101 프로필 create, delete 리팩토링
  src/App.jsx
  src/components/profile/ProfileDeleteModal.jsx
  src/firebase/app.js
  src/pages/ProfileCreate.jsx
  src/pages/ProfilePage.jsx
Labels: refactor

#104 전체적인 리팩토링 및 프로필 페이지 기능 구현
  src/App.jsx
  src/PrivateRoute.jsx
  src/components/footer/Footer.jsx
  src/components/loading/LoadingSpinner.jsx
  src/components/login/LoginForm.jsx
  src/components/logout/LogoutModal.jsx
  src/components/profile/Profile.jsx
  src/components/register/RegisterForm.jsx
  src/firebase/firestore/useCreateAuthUser.js
  src/pages/ProfileEdit.jsx
  src/pages/ProfilePage.jsx
Labels: style, refactor, feat

#105 프로필 페이지 리팩토링
  src/components/profile/Profile.jsx
  src/pages/ProfilePage.jsx
Labels: style, refactor, feat

#107 메인, 검색, 헤더 리팩토링
  index.html
  src/components/carousel/Carousel.jsx
  src/components/carousel/MainBanner.jsx
  src/components/header/Header.jsx
  src/components/modal/Modal.jsx
  src/components/modal/ModalMiddlePortal.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchModal.jsx
  src/components/search/SearchResult.jsx
  src/firebase/firestore/useReadSearchData.js
  src/pages/MainPage.jsx
  src/pages/SearchPage.jsx
Labels: bug, refactor

#112 접근성 개선 및 프로필 삭제 수정
  src/components/button/FormButton.jsx
  src/components/footer/Footer.jsx
  src/components/login/LoginForm.jsx
  src/components/profile/ProfileDeleteModal.jsx
  src/components/register/RegisterForm.jsx
  src/pages/ProfileCreate.jsx
  src/pages/ProfileEdit.jsx
  src/pages/ProfilePage.jsx
Labels: refactor, feat

#113 랜딩페이지 이미지 파이어베이스 연결 및 리팩토링#93
  src/components/landing/CarouselAuto.jsx
  src/components/landing/CarouselAutoFirst.jsx
  src/components/landing/CarouselAutoSecond.jsx
  src/components/landing/CarouselScroll.jsx
  src/containers/landingpage/ScrollSectionAd.jsx
  src/containers/landingpage/ScrollSectionTitle.jsx
  src/pages/LandingPage.jsx
Labels: refactor, remove or edit

#109 프로필 생성 리팩토링
  src/components/profile/Profile.jsx
  src/pages/ProfileCreate.jsx
  src/pages/ProfileEdit.jsx
  src/pages/ProfilePage.jsx
Labels: style, refactor, feat

#115 [refactor] 전체적인 리팩토링
  public/assets/popup/desktop.png
  public/assets/popup/mobile.png
  public/assets/popup/tablet.png
  src/components/carousel/Carousel.jsx
  src/components/carousel/MainBanner.jsx
  src/components/footer/Footer.jsx
  src/components/header/Header.jsx
  src/components/header/LogoModal.jsx
  src/components/landing/CarouselAutoFirst.jsx
  src/components/landing/CarouselAutoSecond.jsx
  src/components/landing/CarouselScroll.jsx
  src/components/loading/SkeletonBanner.jsx
  src/components/loading/SkeletonCarousel.jsx
  src/components/login/LoginForm.jsx
  src/components/modal/Modal.jsx
  src/components/profile/ProfileDeleteModal.jsx
  src/components/register/RegisterForm.jsx
  src/components/search/SearchBar.jsx
  src/components/search/SearchHistory.jsx
  src/components/search/SearchModal.jsx
  src/components/search/SearchPopular.jsx
  src/firebase/firestore/useCreateAuthUser.js
  src/firebase/firestore/useUpdateData.js
  src/firebase/storage/useUploadFile.js
  src/pages/ProfileCreate.jsx
  src/pages/ProfileEdit.jsx
  src/pages/ProfilePage.jsx
  src/styles/ProfileStyles.jsx
  src/styles/SkeletonStyles.jsx
  src/theme/tokens.js
Labels: refactor, remove or edit, chore

#119 전체적인 리팩토링
  .storybook/preview.jsx
  package-lock.json
  package.json
  public/_redirects
  public/assets/landing-img/bg-mobile.png
  public/assets/landing-img/contents-img/fun-food-desktop.png
  public/assets/landing-img/contents-img/fun-food-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-letmein-desktop.png
  public/assets/landing-img/contents-img/fun-letmein-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-manager-desktop.png
  public/assets/landing-img/contents-img/fun-manager-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-quiz-desktop.png
  public/assets/landing-img/contents-img/fun-quiz-mob-and-tabl.png
  public/assets/landing-img/contents-img/fun-shurup-desktop.png
  public/assets/landing-img/contents-img/fun-shurup-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-alchol-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-body-desktop.png
  public/assets/landing-img/contents-img/org-bomul-desktop.png
  public/assets/landing-img/contents-img/org-bomul-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-food-desktop.png
  public/assets/landing-img/contents-img/org-island-desktop.png
  public/assets/landing-img/contents-img/org-island-mob-and-tabl.png
  public/assets/landing-img/contents-img/org-love-desktop.png
  public/assets/landing-img/contents-img/org-love-mob-and-tabl.png
  public/assets/sprite.svg
  src/PrivateRoute.jsx
  src/components/button/FormButton.jsx
  src/components/footer/Footer.jsx
  src/components/forminput/FormInput.jsx
  src/components/register/RegisterForm.jsx
  src/pages/Layout.jsx
  src/pages/ProfilePage.jsx
  src/styles/GlobalStyle.jsx
  src/styles/ProfileStyles.jsx
  src/theme/tokens.js
  src/theme/utils.js
Labels: style, refactor, remove or edit, chore
